baseUrl = ""
title = "Status Network Token Distribution Analysis"
author = "Corey Petty"
canonifyurls = true
theme = "distillpub"

[taxonomies]
# TODO: Taxonomies?

[params]
  description = "Status Network Token Distribution"
  keywords = ["hugo", "distill", "theme"]
  sourcePrefix = "https://github.com/status-im/snt-distribution"

  color = "#4360DF"

  [[params.social]]
  class = "fab fa-github"
  url = "https://github.com/status-im"

  [[params.social]]
  class = "fab fa-twitter"
  url = "https://twitter.com/ethstatus"

[menu]

  [[menu.main]]
  identifier = "about"
  name = "Corey Petty"
  title = "about"
  url = "/about"
  weight = -10
